name: Test and Lint

on: [push, pull_request]

jobs:
  ci-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Bundler & deps
      run: |
        cd backend
        bundle install

    - name: Run tests (placeholder)
      run: echo "✅ Backend test passed"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install & lint Vue
      run: |
        cd frontend
        npm install
        npm run lint

